---
- name: Install Docker on Ubuntu EC2 Instance
  hosts: all
  become: yes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the Docker stable repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add the 'ubuntu' user to the Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

- name: Install Nodejs; clone and start app
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    NODEJS_VERSION: "8"
  tasks:
    - name: Install the nodejs
      apt:
        name: nodejs

    - name: Install the nodejs
      apt:
        name: npm

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/juliusstelldinger/Recap-Projektvorbereitung.git'
        dest: /home/ubuntu/Recap-Projektvorbereitung/

    - name: ls
      ansible.builtin.command: ls /home/ubuntu/

    - name: Install packages based on package.json.
      community.general.npm:
        path: /home/ubuntu/Recap-Projektvorbereitung/02-backend-mini/

    - name: "Install forever (to run Node.js app)."
      npm: name=forever global=yes state=present

    - name: "Check list of Node.js apps running."
      command: forever list
      register: forever_list
      changed_when: false

    - name: "Start example Node.js app."
      command: forever start /home/ubuntu/Recap-Projektvorbereitung/02-backend-mini/index.js
      when: "forever_list.stdout.find('/home/ubuntu/Recap-Projektvorbereitung/02-backend-mini/index.js') == -1"
