name: Deploy Infrastructure

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: 04-iac/terraform

      - name: Terraform Format Check
        run: terraform fmt --check
        working-directory: 04-iac/terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: 04-iac/terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: 04-iac/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: 04-iac/terraform

      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_KEY }}" > /tmp/ssh_key && chmod 400 /tmp/ssh_key

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
        run: |
          export ANSIBLE_PRIVATE_KEY_FILE=/tmp/ssh_key
          ansible-playbook -i inventory.ini docker-playbook.yml
        working-directory: 05-ansible/ansible

      - name: Clean up
        run: rm /tmp/ssh_key
